### ISSUE TITLE
Format doc collection

### ISSUE THREAD

**Issue by booyaa** [booyaa/booyaa.github.io#2]
Starting to see parsing errors in the lunr indexer. Maybe integrate [json-fmt](https://github.com/MaxArt2501/json-fmt) into the build chain?

```
node _lunr/build-index.js < build/js/lunr_docs.json > js/lunr_prebuilt.json
undefined:774
      ,  ],
         ^

SyntaxError: Unexpected token ] in JSON at position 65478
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (/Users/booyaa/Dev/rust/booyaa.github.io/_lunr/build-index.js:14:24)
    at emitNone (events.js:110:20)
    at ReadStream.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
make: *** [build] Error 1
```

**Comment by booyaa** [comment]
workaround's good enough
